time:
  start_timestamp: 2019-02-01T10:00:00.000Z
  physics_step_sec: 300
  output_step_sec: 300
  stop_timestamp: 2019-02-01T12:00:00.000Z
noise:
  init_position_std_km: 1.0e-3
  init_velocity_std_km_p_sec: 1.0e-6
  filter_noise_type: continuous_white_noise
  filter_noise_magnitude: 3.0e-14
  random_seed: os
propagation:
  propagation_model: special_perturbations
  integration_method: RK45
  station_keeping: false
  target_realtime_propagation: true
  sensor_realtime_propagation: true
  realtime_observation: true
  truth_simulation_only: false
geopotential:
  model: egm96.txt
  degree: 4
  order: 4
perturbations:
  third_bodies:
    - sun
    - moon
  solar_radiation_pressure: true
  general_relativity: true
filter:
  name: unscented_kalman_filter
  parameters:
    alpha: 0.05
    beta: 2.0
  dynamics_model: two_body
  maneuver_detection: null
engines_files:
  - engines/all_visible_engine.yaml
events: {}
