time:
  start_timestamp: 2019-02-01T10:00:00.000Z
  physics_step_sec: 300
  output_step_sec: 300
  stop_timestamp: 2019-02-01T12:00:00.000Z
noise:
  init_position_std_km: 1.0e-3
  init_velocity_std_km_p_sec: 1.0e-6
  dynamics_noise_type: simple_noise
  dynamics_noise_magnitude: 1.0e-25
  filter_noise_type: continuous_white_noise
  filter_noise_magnitude: 3.0e-14
  random_seed: null
reward:
  name: CostConstrainedReward
  metrics:
    - name: ShannonInformation
      parameters: {}
    - name: DeltaPosition
      parameters: {}
    - name: LyapunovStability
      parameters: {}
  parameters: {}
decision:
  name: MunkresDecision
  parameters: {}
propagation:
  propagation_model: special_perturbations
  integration_method: 'RK45'
  realtime_propagation: true
  realtime_observation: true
geopotential:
  model: egm96.txt
  degree: 2
  order: 0
perturbations: {}
target_event_set: ""
sensor_event_set: ""
target_set: "targets/two_targets.yaml"
sensor_set: "sensor_networks/geo_optical_only_network.yaml"
