engines_files:
  - engines/cost_constrained_ssn.yaml
events: []
filter:
  dynamics_model: special_perturbations
  maneuver_detection: null
  name: unscented_kalman_filter
  parameters:
    alpha: 0.05
    beta: 2.0
geopotential:
  degree: 4
  model: egm96.txt
  order: 4
noise:
  filter_noise_magnitude: 3.0e-14
  filter_noise_type: continuous_white_noise
  init_position_std_km: 0.001
  init_velocity_std_km_p_sec: 1.0e-06
  random_seed: os
perturbations:
  general_relativity: true
  solar_radiation_pressure: true
  third_bodies:
    - sun
    - moon
propagation:
  integration_method: RK45
  propagation_model: special_perturbations
  sensor_realtime_propagation: true
  station_keeping: false
  target_realtime_propagation: true
  truth_simulation_only: false
time:
  output_step_sec: 60
  physics_step_sec: 60
  start_timestamp: "2018-12-01T12:00:00.000Z"
  stop_timestamp: "2018-12-01T13:00:00.000Z"
