unique_id: 0
decision:
  name: MunkresDecision
  parameters: {}
reward:
  metrics:
    - name: ShannonInformation
      parameters: {}
    - name: DeltaPosition
      parameters: {}
    - name: LyapunovStability
      parameters: {}
  name: CostConstrainedReward
  parameters: {}
sensors_file: sensor_networks/geo_optical_only_network.yaml
targets_file: targets/two_targets.yaml
