decision:
  name: MunkresDecision
  parameters: {}
reward:
  metrics:
    - name: ShannonInformation
      parameters: {}
    - name: DeltaPosition
      parameters: {}
    - name: LyapunovStability
      parameters: {}
  name: CostConstrainedReward
  parameters: {}
sensors_file: sensor_networks/ssn_network.yaml
targets_file: targets/small_target_set.yaml
unique_id: 2
