# ==========================================
# Includes
# ==========================================

include:
  - local: .gitlab/ci/base.gitlab-ci.yml
  - local: .gitlab/ci/rules.gitlab-ci.yml
  - local: .gitlab/ci/scripts.gitlab-ci.yml

# ==========================================
# Base Build Job
# ==========================================

.build-base:
  stage: build
  extends:
    - .rules:default
  artifacts:
    expire_in: 1 hour
  when: on_success

# ==========================================
# Build Python Package Job
# ==========================================

# Build the package in source & binary form, only runs when manifest job succeeds
build-pkg:
  extends:
    - .build-base
    - .python-oldest
  before_script:
    - !reference [.pip-base, before_script]
    - python3 -m pip install build[virtualenv]
  script:
    - !reference [.get-version, script]
    - echo "Building RESONAATE sdits & wheel packages"
    - python3 -m build
  artifacts:
    name: dist
    paths:
      - dist/*.tar.gz
      - dist/*.whl
    reports:
      dotenv: variables.env
  needs:
    - job: manifest
      artifacts: false

# ==========================================
# `sphinx` docs build job
# ==========================================
# Use `sphinx` to build HTML docs

build-docs:
  extends:
    - .build-base
    - .python-oldest
  before_script:
    - !reference [.pip-doc, before_script]
  script:
    - echo "Building documentation with sphinx"
    - cd docs && make clean && make html
  artifacts:
    name: docs
    when: on_success
    paths:
      - docs/build/html
    expose_as: "HTML docs"
    expire_in: 3 days
  needs: []
