# ==========================================
# Includes
# ==========================================

include:
  - local: .gitlab/ci/base.gitlab-ci.yml
  - local: .gitlab/ci/rules.gitlab-ci.yml
  - local: .gitlab/ci/scripts.gitlab-ci.yml

# ==========================================
# Base Check Job
# ==========================================

.check-base:
  stage: check
  extends:
    - .python-oldest
    - .rules:default
  before_script:
    - !reference [.pip-dev, before_script]
  variables:
    # Source files & directories to lint
    LINT_SOURCES: "*.py tests src docs"
  artifacts:
    when: on_failure
    expire_in: 3 days
  needs: []

# ==========================================
# `ruff` Job
# ==========================================
# Lint source code with ruff

ruff:
  extends: .check-base
  script:
    - echo "Linting with ruff"
    - ruff check $LINT_SOURCES --no-fix | tee ruff.log
  artifacts:
    name: ruff
    paths:
      - ruff.log
    expose_as: "ruff log"

# ==========================================
# `check-manifest` job
# ==========================================
# Check Manifest.in for sdist package data

manifest:
  extends: .check-base
  script:
    - echo "Checking sdist files with check-manifest"
    - check-manifest -v | tee manifest.log
  artifacts:
    name: manifest
    paths:
      - manifest.log
    expose_as: "manifest log"
