# ==========================================
# CONDITIONS
# ==========================================

# Merge request pipelines
.mr: &mr
  if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# Pushed tag pipelines
.tag: &tag
  if: $CI_COMMIT_TAG

# Default branch commit pipelines
.branch: &branch
  if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

# Scheduled pipelines
.schedule: &schedule
  if: '$CI_PIPELINE_SOURCE == "schedule"'

# ==========================================
# RULES
# ==========================================

# Default rule: run on all MR, default branch pushes, & tag pushes
.rules:default:
  rules:
    - <<: *tag
    - <<: *branch
    - <<: *mr
    - <<: *schedule
      when: never

# Only on merge requests
.rules:mr:
  rules:
    - *mr
    - <<: *schedule
      when: never

# Only on pushes to default branch
.rules:branch:
  rules:
    - *branch
    - <<: *schedule
      when: never

# Only on pushed tags
.rules:tag:
  rules:
    - *tag
    - <<: *schedule
      when: never

# Always on scheduled jobs, allow manually for merge requests
.rules:scheduled:
  rules:
    - <<: *mr
      when: manual
      allow_failure: true
    - <<: *schedule
