# ==========================================
# Includes
# ==========================================

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

# Exclude 'public' directory, since it just flags a bunch on our auto-documentation
variables:
  SAST_EXCLUDED_PATHS: spec, test, tests, tmp, public, docs, configs, .venv,
  SAST_BANDIT_EXCLUDED_PATHS: "*/tests/*, */.venv/*, */docs/*, */configs/*"
