# ==========================================
# Includes
# ==========================================

include:
  - local: .gitlab/ci/base.gitlab-ci.yml
  - local: .gitlab/ci/rules.gitlab-ci.yml
  - local: .gitlab/ci/scripts.gitlab-ci.yml

# ==========================================
# Base Test Job
# ==========================================

.test-base:
  stage: test
  extends:
    - .python-latest
    - .rules:default
  variables:
    PYTEST_OPTIONS: "-ra -v --durations=5"
  before_script:
    - !reference [.pip-test, before_script]
  artifacts:
    when: always
    expire_in: 1 hour
  when: always
  needs: []

# ==========================================
# Unit Test Job
# ==========================================

pytest-unit:
  extends: .test-base
  variables:
    COVERAGE_FILE: .coverage.unit
    JUNIT_FILE: unit.xml
  script:
    - echo "Running unit tests with pytest"
    - coverage run -m pytest --junitxml=$JUNIT_FILE -m "not (scenario or event)" $PYTEST_OPTIONS
  artifacts:
    paths:
      - .coverage.unit*
    reports:
      junit:
        - $JUNIT_FILE

# ==========================================
# Scenario Test Job
# ==========================================

pytest-scenario:
  extends: .test-base
  variables:
    COVERAGE_FILE: .coverage.scenario
    JUNIT_FILE: scenario.xml
  script:
    - echo "Running scenario tests with pytest"
    - coverage run -m pytest --junitxml=$JUNIT_FILE -m scenario $PYTEST_OPTIONS

  artifacts:
    paths:
      - .coverage.scenario*
    reports:
      junit:
        - $JUNIT_FILE

# ==========================================
# Event Test Job
# ==========================================

pytest-event:
  extends: .test-base
  variables:
    COVERAGE_FILE: .coverage.event
    JUNIT_FILE: event.xml
    PYTEST_MARKS: "-m event"
  script:
    - echo "Running event tests with pytest"
    - coverage run -m pytest --junitxml=$JUNIT_FILE -m event $PYTEST_OPTIONS
  artifacts:
    paths:
      - .coverage.event*
    reports:
      junit:
        - $JUNIT_FILE

# ==========================================
# Coverage Job
# ==========================================

coverage:
  extends: .test-base
  before_script:
    - !reference [.pip-test, before_script]
  script:
    - echo "Combining coverage files from parallel test jobs"
    - coverage combine
    - echo "Creating coverage reports"
    - coverage report
    - coverage html
    - coverage xml
  artifacts:
    name: coverage
    paths:
      - coverage/
    expose_as: Coverage
    expire_in: 1 week
    reports:
      junit: coverage.xml
  needs:
    - pytest-unit
    - pytest-scenario
    - pytest-event
  coverage: /TOTAL.*\s+(\d+\%)/
