# ==========================================
# Includes
# ==========================================

include:
  - local: .gitlab/ci/base.gitlab-ci.yml
  - local: .gitlab/ci/rules.gitlab-ci.yml
  - local: .gitlab/ci/scripts.gitlab-ci.yml

# ==========================================
# Base Test Job
# ==========================================

.test-base:
  stage: test
  extends:
    - .python-latest
    - .rules:default
  variables:
    PYTEST_OPTIONS: "-ra -v --durations=5"
  before_script:
    - !reference [.install-redis, before_script]
    - !reference [.pip-test, before_script]
  artifacts:
    when: always
    expire_in: 1 hour
  when: always
  needs: []

# ==========================================
# Unit Test Job
# ==========================================

pytest-unit:
  extends: .test-base
  variables:
    COVERAGE_FILE: .coverage.unit
    JUNIT_FILE: unit.xml
  script:
    - !reference [.start-redis, script]
    - echo "Running unit tests with pytest"
    - coverage run -m pytest --junitxml=$JUNIT_FILE -m "not (scenario or event)" $PYTEST_OPTIONS
    - !reference [.stop-redis, script]
  artifacts:
    paths:
      - .coverage.unit*
    reports:
      junit:
        - $JUNIT_FILE

# ==========================================
# Scenario Test Job
# ==========================================

pytest-scenario:
  extends: .test-base
  variables:
    COVERAGE_FILE: .coverage.scenario
    JUNIT_FILE: scenario.xml
  script:
    - !reference [.start-redis, script]
    - echo "Running scenario tests with pytest"
    - coverage run -m pytest --junitxml=$JUNIT_FILE -m scenario $PYTEST_OPTIONS
    - !reference [.stop-redis, script]
  artifacts:
    paths:
      - .coverage.scenario*
    reports:
      junit:
        - $JUNIT_FILE

# ==========================================
# Event Test Job
# ==========================================

pytest-event:
  extends: .test-base
  variables:
    COVERAGE_FILE: .coverage.event
    JUNIT_FILE: event.xml
    PYTEST_MARKS: "-m event"
  script:
    - !reference [.start-redis, script]
    - echo "Running event tests with pytest"
    - coverage run -m pytest --junitxml=$JUNIT_FILE -m event $PYTEST_OPTIONS
    - !reference [.stop-redis, script]
  artifacts:
    paths:
      - .coverage.event*
    reports:
      junit:
        - $JUNIT_FILE

# ==========================================
# Coverage Job
# ==========================================

coverage:
  extends: .test-base
  before_script:
    - !reference [.pip-test, before_script]
  script:
    - echo "Calculating unit test coverage"
    - pytest --cov --cov-report=html --cov-report=xml --cov-report=term:skip-covered --cov-context=test -m "not (event or scenario)"
  artifacts:
    name: coverage
    paths:
      - coverage/
    expose_as: Coverage
    expire_in: 1 week
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: /TOTAL.*\s+(\d+.\d+\%)/
  # Allowed to run with scheduled jobs
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_TAG
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
