# ==========================================
# Includes
# ==========================================

include:
  - local: .gitlab/ci/base.gitlab-ci.yml
  - local: .gitlab/ci/rules.gitlab-ci.yml
  - local: .gitlab/ci/scripts.gitlab-ci.yml

# ==========================================
# Base Test Job
# ==========================================

.test-base:
  stage: test
  extends:
    - .python-latest
    - .rules:default
  variables:
    PYTEST_OPTIONS: "-ra -v --durations=5"
  before_script:
    - !reference [.pip-test, before_script]
  artifacts:
    when: always
    expire_in: 1 hour
  when: always
  needs: []

# ==========================================
# Unit Test Job
# ==========================================

pytest-unit:
  extends: .test-base
  script:
    - echo "Running unit tests with pytest"
    - pytest --cov -m "not (integration or regression)" $PYTEST_OPTIONS
  artifacts:
    name: coverage
    paths:
      - coverage/
    expose_as: Coverage
    expire_in: 1 week
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: /TOTAL.*\s+(\d+.\d+\%)/
  # Allowed to run with scheduled jobs
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_TAG
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

# ==========================================
# Integration Test Job
# ==========================================

pytest-integration:
  extends: .test-base
  script:
    - echo "Running integration tests with pytest"
    - pytest --cov -m integration $PYTEST_OPTIONS

# ==========================================
# Regression Test Job
# ==========================================

pytest-regression:
  extends: .test-base
  script:
    - echo "Running regression tests with pytest"
    - pytest --cov -m regression $PYTEST_OPTIONS
