#####################
# Base Job Settings #
#####################

include:
  - local: /.gitlab/ci/common.gitlab-ci.yml

##################
# Script Aliases #
##################

# pip install test tools
# [NOTE]: Editable/Developer install is required here, because the coverage combine/report
#   fails otherwise...
.pip-test: &pip-test
  - python3 -m pip install -e .[test]

# pytest unit test command
.pytest-unit: &pytest-unit
  - COVERAGE_FILE=.coverage.unit coverage run -m pytest --junitxml=unit.xml -m "not (scenario or event)" --durations=5

# pytest scenario integration test command
.pytest-scenario: &pytest-scenario
  - COVERAGE_FILE=.coverage.scenario coverage run -m pytest --junitxml=scenario.xml -m "scenario" --durations=5

# pytest event integration test command
.pytest-event: &pytest-event
  - COVERAGE_FILE=.coverage.event coverage run -m pytest --junitxml=event.xml -m "event" --durations=5

# coverage combine command
.coverage-combine: &coverage-combine
  - coverage combine

# coverage report command
.coverage-report: &coverage-report
  - coverage report
  - coverage html
  - coverage xml

#################
# Base Test Job #
#################

.test-base:
  stage: test
  before_script:
    - !reference [.apt-setup]
    - !reference [.start-redis]
    - !reference [.create-venv]
    - echo -e "\e[0Ksection_start:`date +%s`:pip_test[collapsed=true]\r\e[0K Install resonaate test dependencies via pip"
    - *pip-test
    - echo -e "\e[0Ksection_end:`date +%s`:pip_test\r\e[0K"
  artifacts:
    when: always
    expire_in: 1 week
  when: always
  needs: []

#################
# Unit Test Job #
#################

pytest:unit:
  extends: .test-base
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:pytest_unit[collapsed=true]\r\e[0K Unit test code with pytest"
    - *pytest-unit
    - echo -e "\e[0Ksection_end:`date +%s`:pytest_unit\r\e[0K"
    - !reference [.stop-redis]
  artifacts:
    paths:
      - .coverage.unit*
    reports:
      junit:
        - unit.xml

#####################
# Scenario Test Job #
#####################

pytest:scenario:
  extends: .test-base
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:pytest_scenario[collapsed=true]\r\e[0K Scenario integration tests"
    - *pytest-scenario
    - echo -e "\e[0Ksection_end:`date +%s`:pytest_scenario\r\e[0K"
    - !reference [.stop-redis]
  artifacts:
    paths:
      - .coverage.scenario*
    reports:
      junit:
        - scenario.xml

##################
# Event Test Job #
##################

pytest:event:
  extends: .test-base
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:pytest_event[collapsed=true]\r\e[0K Event integration tests"
    - *pytest-event
    - echo -e "\e[0Ksection_end:`date +%s`:pytest_event\r\e[0K"
    - !reference [.stop-redis]
  artifacts:
    paths:
      - .coverage.event*
    reports:
      junit:
        - event.xml

#########################
# Coverage Analysis Job #
#########################

coverage-report:
  extends: .test-base
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:cov_combine[collapsed=true]\r\e[0K Combine coverage files from test jobs"
    - *coverage-combine
    - echo -e "\e[0Ksection_end:`date +%s`:cov_combine\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:cov_report[collapsed=true]\r\e[0K Create coverage reports (CLI, HTML, XML)"
    - *coverage-report
    - echo -e "\e[0Ksection_end:`date +%s`:cov_report\r\e[0K"
    - !reference [.stop-redis]
  artifacts:
    paths:
      - coverage/
    expose_as: Coverage
    reports:
      cobertura: coverage.xml
  needs:
    - pytest:unit
    - pytest:scenario
    - pytest:event
  coverage: /TOTAL.*\s+(\d+\%)/
